#!/bin/bash
# chkconfig: 2345 90 10
#description: Redis server

PORT=6379
PASSWORD=123456

EXEC=/usr/local/bin/redis-server
CLIEXEC=/usr/local/bin/redis-cli

PIDFILE=/var/run/redis_${PORT}.pid
CONF="/etc/redis/redis.conf"

case "$1" in
	start)
		if [ -f $PIDFILE ]
		then
			echo "$PIDFILE exists, process is already running or crashed"
		else
			echo "Starting Redis server..."
			$EXEC $CONF
		fi
		;;
	stop)
		if [ ! -f $PIDFILE ]
		then
			echo "$PIDFILE dones not exists, process is not running"
		else
			PID=$(cat $PIDFILE)
			echo "Stoping …"
			$CLIEXEC -h 0.0.0.0 -p $PORT -a $PASSWORD shutdown
			while [ -x /proc/${PID} ]
			do
				echo "Waiting for Redis to shutdown ……"
				sleep 1
			done
			rm -f $PIDFILE
			echo "Redis stopped"
		fi
		;;
	restart)
		# Stop the service and regardless of whether it was
		# running or not, start it again.
		if $0 stop  "$@"; then
		  if ! $0 start "$@"; then
			echo "Failed to restart server."
			exit 1
		  fi
		else
		  echo "Failed to stop running server, so refusing to try to start."
		  exit 1
		fi
		;;
	*)
		echo "Please use start|stop|restart as first argument"
        ;;
esac